In [1]:
# load data, run Stage 1 (quality) and Stage 2 (Kalman)
import sys
sys.path.append("../src")

import numpy as np
import pandas as pd
from data_quality import run_quality_checks
from kalman_filter import run_kalman_stage

raw = pd.read_csv("../data/member1_raw_sensor_stream.csv")
filtered = run_kalman_stage(run_quality_checks(raw))


ref = pd.read_csv("../data/member1_sensor_health.csv")
filtered = filtered.merge(ref[["record_id", "run_id"]], on="record_id", how="left")
filtered["fault"] = filtered["run_id"].str.split("-").str[2]

print("Rows:", len(filtered))
print(filtered["fault"].value_counts())

Rows: 2941
fault
DUS    593
PAR    591
OPE    588
SHO    586
NOR    583
Name: count, dtype: int64

In [2]:
# INDICATORS and make_indicators()
from panel_model import expected_current, expected_temp_rise, LOAD_OHMS

INDICATORS = {
    "power_ratio": "benefit",   # power compared to a healthy panel
    "voltage_ratio": "benefit", # voltage compared to a healthy panel
    "current_ratio": "benefit", # current compared to a healthy panel
    "temp_rise": "cost",        # panel temp rise above a healthy panel
    "dust_level": "cost",       # dust sensor output
}


def make_indicators(df):
    # compare each reading with a HEALTHY panel at the same light and temperature
    # (physics model in panel_model.py), 1 = as good as a healthy panel
    df = df.copy()
    i_exp = np.clip(expected_current(df["irradiance_lux"], df["panel_temp1_c"]), 0.1, None)
    v_exp = i_exp / 1000 * LOAD_OHMS

    df["power_ratio"] = (df["power_mw"] / (i_exp * v_exp)).clip(0, 1)
    df["voltage_ratio"] = (df["voltage_v"] / v_exp).clip(0, 1)
    df["current_ratio"] = (df["current_ma"] / i_exp).clip(0, 1)

    # temp rise ABOVE what a healthy panel gets in this sunlight
    panel_cols = [c for c in ["panel_temp1_c", "panel_temp2_c"] if c in df.columns]
    panel_temp = df[panel_cols].mean(axis=1)
    df["temp_rise"] = panel_temp - df["ambient_temp_c"] - expected_temp_rise(df["irradiance_lux"])

    # my device gives dust in % (DSM501B), the old dataset had volts (GP2Y10)
    df["dust_level"] = df["dust_lpo_pct"] if "dust_lpo_pct" in df.columns else df["dust_vo_v"]
    return df


# ---- test make_indicators() ----
ind = make_indicators(filtered)

# 1) why we compare with a healthy panel: raw power changes a lot with the light,
#    but a normal panel is always close to 1
normal = ind[ind["fault"] == "NOR"]
print("NORMAL panels only:")
print("  raw power_mw   : min", round(normal["power_mw"].min(), 1), " max", round(normal["power_mw"].max(), 1))
print("  power_ratio    : min", round(normal["power_ratio"].min(), 2), " max", round(normal["power_ratio"].max(), 2))
print()

# 2) a normal panel also gets warm in the sun - this part is taken out of temp_rise
print("NORMAL panels, panel minus air: median", round((normal["panel_temp1_c"] - normal["ambient_temp_c"]).median(), 1), "C",
      "-> temp_rise after the sunlight part:", round(normal["temp_rise"].median(), 1), "C")
print()

# 3) median of each indicator for each fault type
print("Median indicator value for each fault type:")
ind.groupby("fault")[list(INDICATORS)].median().round(2)

NORMAL panels only:
  raw power_mw   : min 105.9  max 237.5
  power_ratio    : min 0.9  max 1.0

NORMAL panels, panel minus air: median 8.1 C -> temp_rise after the sunlight part: -1.5 C

Median indicator value for each fault type:

       power_ratio  voltage_ratio  current_ratio  temp_rise  dust_level
fault
DUS           0.74           0.86           0.86      -0.44       15.99
NOR           1.00           1.00           1.00      -1.50        2.68
OPE           0.00           0.00           0.00      -0.39        2.61
PAR           0.79           0.89           0.89      -0.73        1.70
SHO           0.90           0.95           1.00       0.29        1.81

In [3]:
# normalize()

def normalize(df):
    norm = pd.DataFrame(index=df.index)
    for col, direction in INDICATORS.items():
        lo, hi = df[col].min(), df[col].max()
        if direction == "benefit":
            norm[col] = (df[col] - lo) / (hi - lo)
        else:
            norm[col] = (hi - df[col]) / (hi - lo)
    return norm


# ---- test normalize() ----
norm = normalize(ind)

# 1) every indicator is now between 0 and 1
print("Range after normalize:")
print(norm.describe().loc[["min", "max"]].round(2))
print()

# 2) "cost" indicators are flipped: high dust -> LOW score
row_dusty = ind["dust_level"].idxmax()
row_clean = ind["dust_level"].idxmin()
print(f"Dustiest reading: dust_level {ind.loc[row_dusty, 'dust_level']:.3f}  ->  normalized {norm.loc[row_dusty, 'dust_level']:.2f}")
print(f"Cleanest reading: dust_level {ind.loc[row_clean, 'dust_level']:.3f}  ->  normalized {norm.loc[row_clean, 'dust_level']:.2f}")
print()

# 3) the same fault table, after normalize (1 = healthy, 0 = bad)
norm["fault"] = ind["fault"]
print("Median after normalize (1 = healthy, 0 = bad):")
norm.groupby("fault")[list(INDICATORS)].median().round(2)

Range after normalize:
     power_ratio  voltage_ratio  current_ratio  temp_rise  dust_level
min          0.0            0.0            0.0        0.0         0.0
max          1.0            1.0            1.0        1.0         1.0

Dustiest reading: dust_level 25.340  ->  normalized 0.00
Cleanest reading: dust_level 0.100  ->  normalized 1.00

Median after normalize (1 = healthy, 0 = bad):

       power_ratio  voltage_ratio  current_ratio  temp_rise  dust_level
fault
DUS           0.74           0.86           0.86       0.31        0.37
NOR           1.00           1.00           1.00       0.41        0.90
OPE           0.00           0.00           0.00       0.31        0.90
PAR           0.79           0.89           0.89       0.34        0.94
SHO           0.90           0.95           1.00       0.24        0.93

In [4]:
# entropy_weights()

def entropy_weights(norm):
    # step 1: share of each reading in the column
    p = (norm + 1e-12) / (norm + 1e-12).sum()

    
    n = len(norm)
    entropy = -(p * np.log(p)).sum() / np.log(n)

    # step 3: weight from "1 - entropy" (the information part)
    info = 1 - entropy
    return info / info.sum()


# ---- test 1: tiny example to see the idea ----
tiny = pd.DataFrame({
    "A_same":   [0.5, 0.5, 0.5, 0.5],
    "B_little": [0.4, 0.5, 0.5, 0.6],
    "C_a_lot":  [0.0, 0.1, 0.9, 1.0],
})
print("Tiny example weights:")
print(entropy_weights(tiny).round(3))
print()

# ---- test 2: real data ----
indicator_cols = list(INDICATORS)
weights = entropy_weights(norm[indicator_cols])
print("Real weights (sum =", round(weights.sum(), 3), "):")
print(weights.sort_values(ascending=False).round(3))
print()

# ---- final check: notebook code = src/entropy_weighting.py ----
import entropy_weighting
w_file = entropy_weighting.entropy_weights(entropy_weighting.normalize(entropy_weighting.make_indicators(filtered)))
print("Notebook code = src/entropy_weighting.py:", np.allclose(weights.values, w_file[indicator_cols].values))

Tiny example weights:
A_same      0.000
B_little    0.019
C_a_lot     0.981
dtype: float64

Real weights (sum = 1.0 ):
power_ratio      0.324
voltage_ratio    0.307
current_ratio    0.200
temp_rise        0.121
dust_level       0.049
dtype: float64

Notebook code = src/entropy_weighting.py: True