In [1]:
# load data, run Stage 1 (quality) and Stage 2 (Kalman)
import sys
sys.path.append("../src")

import numpy as np
import pandas as pd
from data_quality import run_quality_checks
from kalman_filter import run_kalman_stage

raw = pd.read_csv("../data/member1_raw_sensor_stream.csv")
filtered = run_kalman_stage(run_quality_checks(raw))


ref = pd.read_csv("../data/member1_sensor_health.csv")
filtered = filtered.merge(ref[["record_id", "run_id"]], on="record_id", how="left")
filtered["fault"] = filtered["run_id"].str.split("-").str[2]

print("Rows:", len(filtered))
print(filtered["fault"].value_counts())

Rows: 2941
fault
DUS    593
PAR    591
OPE    588
SHO    586
NOR    583
Name: count, dtype: int64

In [2]:
# INDICATORS and make_indicators()

INDICATORS = {
    "power_ratio": "benefit",   # power per unit of sunlight
    "voltage_ratio": "benefit", # voltage compared to a healthy panel
    "current_ratio": "benefit", # current per unit of sunlight
    "temp_rise": "cost",        # panel temp minus air temp
    "dust_level": "cost",       # dust sensor output
}


def make_indicators(df):
    df = df.copy()
    irr = (df["irradiance_lux"] / 120).clip(lower=1)   # W/m2 (data contract: lux / 120)

    power_per_irr = df["power_mw"] / irr
    current_per_irr = df["current_ma"] / irr

    # healthy reference = 95th percentile, so a few high values do not decide it
    df["power_ratio"] = (power_per_irr / power_per_irr.quantile(0.95)).clip(0, 1)
    df["current_ratio"] = (current_per_irr / current_per_irr.quantile(0.95)).clip(0, 1)
    df["voltage_ratio"] = (df["voltage_v"] / df["voltage_v"].quantile(0.95)).clip(0, 1)

    # average of the panel temperature sensors we have (1 on our device, 2 in the dataset)
    panel_cols = [c for c in ["panel_temp1_c", "panel_temp2_c"] if c in df.columns]
    panel_temp = df[panel_cols].mean(axis=1)
    df["temp_rise"] = panel_temp - df["ambient_temp_c"]

    # my device gives dust in % (DSM501B), the old dataset had volts (GP2Y10)
    df["dust_level"] = df["dust_lpo_pct"] if "dust_lpo_pct" in df.columns else df["dust_vo_v"]
    return df


# ---- test make_indicators() ----
ind = make_indicators(filtered)

# 1) why we divide by sunlight: raw power vs power_ratio for normal panels
normal = ind[ind["fault"] == "NOR"]
print("NORMAL panels only:")
print("  raw power_mw   : min", round(normal["power_mw"].min(), 1), " max", round(normal["power_mw"].max(), 1))
print("  power_ratio    : min", round(normal["power_ratio"].min(), 2), " max", round(normal["power_ratio"].max(), 2))
print()

# 2) median of each indicator for each fault type
print("Median indicator value for each fault type:")
ind.groupby("fault")[list(INDICATORS)].median().round(2)

NORMAL panels only:
  raw power_mw   : min 105.9  max 237.5
  power_ratio    : min 0.33  max 1.0

Median indicator value for each fault type:

       power_ratio  voltage_ratio  current_ratio  temp_rise  dust_level
fault
DUS           0.45           0.83           0.59       7.18       15.99
NOR           0.85           0.97           0.70       8.10        2.68
OPE           0.00           0.00           0.00      11.83        2.61
PAR           0.53           0.85           0.48       8.25        1.70
SHO           0.27           0.20           1.00       5.05        1.81

In [3]:
# normalize()

def normalize(df):
    norm = pd.DataFrame(index=df.index)
    for col, direction in INDICATORS.items():
        lo, hi = df[col].min(), df[col].max()
        if direction == "benefit":
            norm[col] = (df[col] - lo) / (hi - lo)
        else:
            norm[col] = (hi - df[col]) / (hi - lo)
    return norm


# ---- test normalize() ----
norm = normalize(ind)

# 1) every indicator is now between 0 and 1
print("Range after normalize:")
print(norm.describe().loc[["min", "max"]].round(2))
print()

# 2) "cost" indicators are flipped: high dust -> LOW score
row_dusty = ind["dust_level"].idxmax()
row_clean = ind["dust_level"].idxmin()
print(f"Dustiest reading: dust_level {ind.loc[row_dusty, 'dust_level']:.3f}  ->  normalized {norm.loc[row_dusty, 'dust_level']:.2f}")
print(f"Cleanest reading: dust_level {ind.loc[row_clean, 'dust_level']:.3f}  ->  normalized {norm.loc[row_clean, 'dust_level']:.2f}")
print()

# 3) the same fault table, after normalize (1 = healthy, 0 = bad)
norm["fault"] = ind["fault"]
print("Median after normalize (1 = healthy, 0 = bad):")
norm.groupby("fault")[list(INDICATORS)].median().round(2)

Range after normalize:
     power_ratio  voltage_ratio  current_ratio  temp_rise  dust_level
min          0.0            0.0            0.0        0.0         0.0
max          1.0            1.0            1.0        1.0         1.0

Dustiest reading: dust_level 25.340  ->  normalized 0.00
Cleanest reading: dust_level 0.100  ->  normalized 1.00

Median after normalize (1 = healthy, 0 = bad):

       power_ratio  voltage_ratio  current_ratio  temp_rise  dust_level
fault
DUS           0.45           0.83           0.59       0.69        0.37
NOR           0.85           0.97           0.70       0.65        0.90
OPE           0.00           0.00           0.00       0.49        0.90
PAR           0.53           0.85           0.48       0.65        0.94
SHO           0.27           0.20           1.00       0.79        0.93

In [4]:
# entropy_weights()

def entropy_weights(norm):
    # step 1: share of each reading in the column
    p = (norm + 1e-12) / (norm + 1e-12).sum()

    
    n = len(norm)
    entropy = -(p * np.log(p)).sum() / np.log(n)

    # step 3: weight from "1 - entropy" (the information part)
    info = 1 - entropy
    return info / info.sum()


# ---- test 1: tiny example to see the idea ----
tiny = pd.DataFrame({
    "A_same":   [0.5, 0.5, 0.5, 0.5],
    "B_little": [0.4, 0.5, 0.5, 0.6],
    "C_a_lot":  [0.0, 0.1, 0.9, 1.0],
})
print("Tiny example weights:")
print(entropy_weights(tiny).round(3))
print()

# ---- test 2: real data ----
indicator_cols = list(INDICATORS)
weights = entropy_weights(norm[indicator_cols])
print("Real weights (sum =", round(weights.sum(), 3), "):")
print(weights.sort_values(ascending=False).round(3))
print()

# ---- final check: notebook code = src/entropy_weighting.py ----
import entropy_weighting
w_file = entropy_weighting.entropy_weights(entropy_weighting.normalize(entropy_weighting.make_indicators(filtered)))
print("Notebook code = src/entropy_weighting.py:", np.allclose(weights.values, w_file[indicator_cols].values))

Tiny example weights:
A_same      0.000
B_little    0.019
C_a_lot     0.981
dtype: float64

Real weights (sum = 1.0 ):
voltage_ratio    0.339
power_ratio      0.339
current_ratio    0.213
temp_rise        0.067
dust_level       0.042
dtype: float64

Notebook code = src/entropy_weighting.py: True